### ISSUE TITLE
Internal request route not base on weight but replica count

### ISSUE THREAD

**Issue by StyleTang** [argoproj/rollouts-demo#43]
Hi Team,
I tested `examples/istio-subset`, it is a canary(subset) rollout.
Assume only 1 replica.

if I go to step 1:
```yaml
      steps:
      - setWeight: 10
      - pause: {}         # pause indefinitely
```
Then env is:
`canary` pod count : 1 
`canary` weight: 10 %
`stable` pod count : 1 
`stable` weight: 90 %

**If I use internal host, like `http://istio-rollout.rollouts-demo-istio.svc.cluster.local/color`, then the issue happens, the real traffic is 50% vs 50%, not base on `weight` but `pod count`.**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: istio-rollout
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: istio-rollout
```

======================================================================

But if I use external host, it has no issue, like `http://istio-rollout.apps.argoproj.io/color`, the traffic dispatch works well. canary 10% vs stable 90%
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: istio-rollout-vsvc
spec:
  gateways:
  - istio-rollout-gateway
  hosts:
  - istio-rollout.apps.argoproj.io
  - istio-rollout.local
 ```

Do you guys encounter this issue before? Or I made some mistake here?
Thanks for taking time to read this issue.
